spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://leoaliyun:3306/local_xgzx?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
#家庭计算机  mysql 5.7  root  root  , aliyun mysql 8.0   root  root
#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://192.168.121.38:3306/xgzx?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
#    username: root
#    password: root

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.tiza.leo.mybatis.springboot_mybatis_xml.model