#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://192.168.121.38:3306/xgzx?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
#    username: root
#    password: root
#家庭计算机  root  root  , aliyun   root  root
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://leoaliyun:3306/local_xgzx?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root

mybatis:
  type-aliases-package: com.tiza.leo.mybatis.springboot_mybatis_annotation.model
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl